version: '3.7'

services:

  #mongo_course_python
  mongo_course_python:
    container_name: 'mongo_course_python'
    build:
      context: .
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - mongo_course_network

  #mongo_course_database
  mongo_course_database:
    container_name: mongo_course_database
    build:
      context: docker/mongo
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: MongoCourse
    ports:
      - 27018:27017
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo_course_network
    command: [ "--replSet", "rs0" ]

#Docker Networks
networks:
  mongo_course_network:
    name: mongo_course_network